apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "je-deel-test.fullname" . }}
  labels:
    {{- include "je-deel-test.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "je-deel-test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "je-deel-test.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5001
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "je-deel-test.fullname" . }}-config
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "je-deel-test.fullname" . }}
