replicaCount: 5
image:
  repository: jezenith/je-deel-test
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
  targetPort: 5001
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"
storage:
  accessModes: ReadWriteOnce
  size: 3Gi
