# Default values for je-deel-test-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: jezenith/je-deel-test
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 5001
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

deployment:
  annotations: {}
  labels: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 15
  targetCPUUtilizationPercentage: 80

strategy:
  type: RollingUpdate
  maxUnavailable: 1
  maxSurge: 4

container:
  name: je-deel-test
  port: 5001

volumes:
  name: data
  mountPath: /data
  persistentVolumeClaim:
    claimName: je-deel-pvc
