replicaCount: 6
image:
  repository: jezenith/je-deel-test
  tag: latest  # Consider parameterizing this
service:
  type: LoadBalancer
  port: 80
  targetPort: 5001
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"
livenessProbe:
  httpGet:
    path: /health
    port: 5001
  initialDelaySeconds: 15
  periodSeconds: 15
readinessProbe:
  httpGet:
    path: /health
    port: 5001
  initialDelaySeconds: 5
  periodSeconds: 5
