apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "je-deel-test-chart.fullname" . }}
  labels:
    app: {{ include "je-deel-test-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
      maxSurge: {{ .Values.strategy.maxSurge }}
  selector:
    matchLabels:
      app: {{ include "je-deel-test-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "je-deel-test-chart.fullname" . }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
        volumeMounts:
        - mountPath: {{ .Values.volumes.mountPath }}
          name: {{ .Values.volumes.name }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
      volumes:
      - name: {{ .Values.volumes.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.persistentVolumeClaim.claimName }}
