apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "je-deel-test-chart.fullname" . }}
  labels:
    app: {{ include "je-deel-test-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ include "je-deel-test-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "je-deel-test-chart.fullname" . }}
    spec:
     containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
