apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "je-deel-test-chart.fullname" . }}
  labels:
    app: {{ include "je-deel-test-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 4
  selector:
    matchLabels:
      app: {{ include "je-deel-test-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "je-deel-test-chart.fullname" . }}
    spec:
      containers:
      - name: je-deel-test
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        volumeMounts:
        - mountPath: "/data"
          name: data
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: je-deel-pvc
