apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "je-deel-test.fullname" . }}
  labels:
    app: {{ include "je-deel-test.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "je-deel-test.fullname" . }}
  minReplicas: 2
  maxReplicas: {{ .Values.replicaCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
