apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "je-deel-test.fullname" . }}-pvc
  labels:
    {{- include "je-deel-test.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
