apiVersion: v1
kind: Service
metadata:
  name: {{ include "je-deel-test-chart.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "je-deel-test-chart.fullname" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
