apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: amU=  
  password: MTIzNDU2Nzg=  
---
apiVersion: v1
kind: Service
metadata:
  name: je-deel-test-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: je-deel-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: je-deel-test-deployment
  labels:
    app: je-deel-test
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: je-deel-test
  template:
    metadata:
      labels:
        app: je-deel-test
    spec:
      containers:
      - name: je-deel-test
        image: jezenith/je-deel-test:latest
        ports:
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        env:
        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
