apiVersion: v1
kind: Service
metadata:
  name: je-deel-test-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: je-deel-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001