apiVersion: apps/v1
kind: Deployment
metadata:
  name: je-deel-test-deployment
  labels:
    app: je-deel-test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: je-deel-test
  template:
    metadata:
      labels:
        app: je-deel-test
    spec:
      containers:
      - name: je-deel-test
        image: jezenith/je-deel-test:latest
        ports:
        - containerPort: 5001
        volumeMounts:
        - mountPath: "/data"
          name: data
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-claim