apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: je-deel-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 3Gi
