apiVersion: v1
kind: Service
metadata:
  name: je-deel-test-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: je-deel-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: je-deel-test-deployment
  labels:
    app: je-deel-test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: je-deel-test
  template:
    metadata:
      labels:
        app: je-deel-test
    spec:
      containers:
      - name: je-deel-test
        image: jezenith/je-deel-test:test-6.2
        ports:
        - containerPort: 5001
        volumeMounts:
        - mountPath: "/app/instance"
          name: data
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-claim
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 3Gi