apiVersion: apps/v1
kind: Deployment
metadata:
  name: je-deel-test-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: je-deel-test
  template:
    metadata:
      labels:
        app: je-deel-test
    spec:
      containers:
      - name: je-deel-test
        image: jezenith/je-deel-test:test-4
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/app
        - name: sqlite-volume
          mountPath: /app/instance
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 15
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: log-pvc
      - name: sqlite-volume
        persistentVolumeClaim:
          claimName: sqlite-pvc
